Update LejosApp.java
LehtonenKalle/palikka-posse-project pull request #15
Opened 2024-04-18 07:10 UTC by NikoLaaks

added comment

2024-04-18 07:16 UTC, joni23008 requested changes

2024-04-19 14:29 UTC, LehtonenKalle approved these changes
Good change

2024-04-21 09:23 UTC, LehtonenKalle approved these changes

2024-04-22 06:42 UTC, joni23008 commented
very good.

2024-04-22 06:43 UTC, joni23008 approved these changes
nice!

2024-04-22 06:43 UTC, merged